#!/usr/bin/env node
// Generates config.js (loaded by index.html) from .env or from environment variables.
//
// node build-config.js
//
// WHY EXIST?: This is a static site with no bundler, and browsers can't read .env files. 
// This script turns .env into a tiny config.js (gitignored) at build time.
// In CI / hosting dashboards, set SUPABASE_URL and SUPABASE_ANON_KEY as environment
// variables/secrets and run this script as the build step.

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const REQUIRED = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];

function parseEnvFile(file) {
    const out = {};
    if (!fs.existsSync(file)) return out;
    for (const rawLine of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
        const line = rawLine.trim();
        if (!line || line.startsWith('#')) continue;
        const eq = line.indexOf('=');
        if (eq === -1) continue;
        const key = line.slice(0, eq).trim().replace(/^export\s+/, '');
        let value = line.slice(eq + 1).trim();
        if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
            value = value.slice(1, -1);
        }
        out[key] = value;
    }
    return out;
}

function fail(message) {
    console.error('\n✖ build-config: ' + message + '\n');
    process.exit(1);
}

// Real environment variables win over .env, so CI secrets override local files.
const fromFile = parseEnvFile(path.join(ROOT, '.env'));
const config = {};
for (const key of REQUIRED) {
    config[key] = (process.env[key] || fromFile[key] || '').trim();
}

const missing = REQUIRED.filter(k => !config[k]);
if (missing.length) {
    fail(`Missing ${missing.join(', ')}. Create a .env file (see .env.example) or set them as environment variables.`);
}

if (!/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(config.SUPABASE_URL)) {
    console.warn('! SUPABASE_URL does not look like https://<project-ref>.supabase.co — double-check it.');
}

// Safety net: refuse to ship an admin key to the browser.
try {
    const payload = JSON.parse(Buffer.from(config.SUPABASE_ANON_KEY.split('.')[1], 'base64url').toString('utf8'));
    if (payload.role && payload.role !== 'anon') {
        fail(`SUPABASE_ANON_KEY has role "${payload.role}". Only the public "anon" key may be used in a browser app.`);
    }
} catch (_) {
    console.warn('! Could not read SUPABASE_ANON_KEY as a JWT — make sure it is the anon/public key.');
}

const output =
    '// AUTO-GENERATED by build-config.js from .env — do not edit or commit.\n' +
    'window.APP_CONFIG = ' + JSON.stringify(config, null, 2) + ';\n';

fs.writeFileSync(path.join(ROOT, 'config.js'), output);
console.log('✔ config.js generated (' + REQUIRED.join(', ') + ')');
